### ISSUE TITLE
Opens only in a small part of the screen

### ISSUE THREAD

**Issue by bhavikbhavsar** [LekoArts/gatsby-starter-portfolio-jodie#11]
![image](https://user-images.githubusercontent.com/4545441/54423459-bb700e80-4736-11e9-9e19-c53ff65757bc.png)

**Comment by LekoArts** [comment]
Can't reproduce that. Do you have more information at hand?

**Comment by LekoArts** [comment]
Closing this issue then. If you still see that problem: Please provide more information on how to re-create that issue.
