### ISSUE TITLE
Instagram doesn't get called during build?

### ISSUE THREAD

**Issue by GarrettJMU** [LekoArts/gatsby-starter-portfolio-jodie#119]
This may be outside of the scope of this project (and may be an issue with gatsby-source-plugin or just user error :) ). 

I have my FB App in development mode, I can build it locally with `yarn start` and no issue. 

If I keep it in development and deploy to netlify, it doesn't get any data from Instagram.

If I flip the switch on the FB app to production I fail to build for both local and netlify.

Any suggestions?

**Comment by GarrettJMU** [comment]
Also to add to this `gatsby build && gatsby serve` will display instagram correctly locally.

**Comment by LekoArts** [comment]
Glad that you could figure it out :)
