### ISSUE TITLE
React warnings following auto-updates

### ISSUE THREAD

**Issue by multidis** [LekoArts/gatsby-starter-portfolio-jodie#165]
Following recent auto-updates there are warnings in the console, for example:

> Warning: componentWillMount has been renamed ...

`SideEffect(NullComponent)` component is mentioned.

@LekoArts any idea which dependency this could be related to?

**Comment by LekoArts** [comment]
Please open up an issue on Gatsby's repository as this is not related to this starter. Thanks!

**Comment by multidis** [comment]
Indeed I see now, it appears to be unrelated to the starter, sorry for opening here.
https://github.com/gatsbyjs/gatsby/issues/17865
https://github.com/gatsbyjs/gatsby/issues/10179
