### ISSUE TITLE
Template display issues in microsoft edge

### ISSUE THREAD

**Issue by conradlin** [LekoArts/gatsby-starter-portfolio-jodie#238]
Hi, I've been enjoying this template for starting out with gatsby on my personal site, but I noticed that it has display issues on microsoft edge (you can test this even with the demo site). Is there any suggested way to handle these cases?

**Comment by schellack** [comment]
I've run into that issue before myself. I believe I relied on [this comment](https://github.com/LekoArts/gatsby-starter-portfolio-jodie/issues/10#issuecomment-482813092) to help resolve the issue.

**Comment by conradlin** [comment]
Thank you @schellack - it works great for desktop. If I may ask, how did you deal with: 

@media (min-width: calc(${props => props.theme.breakpoints[2]} + 1px))

The comment referred doesn't mention how to maintain the responsiveness of the site as the size of the window shrinks past the breakpoints.

**Comment by conradlin** [comment]
Also, I have noticed that if I simply change this styled component 

const Main = styled.main`
  @media (min-width: calc(${props => props.theme.breakpoints[2]} + 1px)) {
    grid-column-start: 2;
  }
`

to 

const Main = styled.main`
    grid-column-start: 2;
`

The elements load well on edge/IE desktop, but have issues with the responsiveness after the size of the window gets smaller than the breakpoints.

**Comment by schellack** [comment]
@conradlin I also had to add a rule just for Edge like this in `layout.tsx` (starting with `@supports`):
```javascript
const Main = styled.div`
  @media (min-width: calc(${props => props.theme.breakpoints[2]} + 1px)) {
    grid-column-start: 2;
  }
  @supports (-ms-ime-align:auto) {
    @media (min-width: ${props => props.theme.breakpoints[2] + 1}px) {
      grid-column-start: 2;
    }
  }
`
```

**Comment by schellack** [comment]
(in case you're wondering "why": Edge has a bug with calc(), so that works around the bug)

**Comment by conradlin** [comment]
Works like a charm @schellack . Thank you so much for taking the time to help me out. FYI, I found that you could do a styled.main and it still works. So my code looks like this:

`const Main = styled.main`
@media (min-width: calc(${props => props.theme.breakpoints[2]} + 1px)) {
  grid-column-start: 2;
}
@supports (-ms-ime-align:auto) {
  @media (min-width: ${props => props.theme.breakpoints[2] + 1}px) {
    grid-column-start: 2;
  }
}
``

You're the best!
