### ISSUE TITLE
What is PAGE_ID via the Facebook Graph API Explorer?

### ISSUE THREAD

**Issue by markkohdev** [LekoArts/gatsby-starter-portfolio-jodie#239]
When trying to follow the instructions to connect my instagram account I'm having trouble with this step:
> Make a GET request with "PAGE_ID?fields=access_token"

I have my extended `ACCESS_TOKEN` and have pasted it into the "Access Token" field of the graph api explorer, but if I try to query `PAGE_ID?fields=access_token` then I get this error:
```
{
  "error": {
    "message": "(#803) Some of the aliases you requested do not exist: PAGE_ID",
    "type": "OAuthException",
    "code": 803,
    "fbtrace_id": "-------"
  }
}
```

I figured that maybe you weren't being literal about `PAGE_ID` but when I try to replace that with my instagram username or even my instagram User ID I get the same error.

Am I doing something wrong here?  What is `PAGE_ID` supposed to be?

P.S: Thank you for this dank-ass theme!!  I'm super psyched to try it out :)

**Comment by EdinK1** [comment]
Hey @markkohdev. You can find the PAGE_ID by going to your Facebook page and copying it from the url. When you go to your Facebook page the link should look something like this: 
`https://www.facebook.com/[PAGE_NAME]-[PAGE_ID].`

Once you get the PAGE_ID your GET request should look like this: 

`[PAGE_ID]?fields=access_token`

**Comment by markkohdev** [comment]
Hey @EdinK1 thanks for the advice, that worked! 👍 

I realize now that the instructions saying you need a "Facebook page" meant like a legit [Facebook Page](https://www.facebook.com/pages/creation/).  I thought it just meant a facebook account haha.  I also wouldn't have guessed where to get that Page ID, but I found [these instructions](https://www.facebook.com/help/1503421039731588) which show a more concrete way.  

I'll make a PR to clarify these steps in the README a bit :)

Only issue now is that I'm getting a build error when trying to download a video thumbnail from my instagram:
```
Could not download file, error is failed to process https://scontent.xx.fbcdn.net/v/t51.2885-15/73361718_818196845303162_1316219678019164773_n.jpg?_nc_cat=102&_nc_oc=AQmjPJNNgm8unhpcyubLN3jXSPCWig7AfNdYRk6MR1vyspOEeC-2OokEXi8mdJyhCSU&_nc_ht=scontent.xx&oh=eeb52366cceef0ea0dab602afe9d3520&oe=5ECFA488
RequestError: getaddrinfo ENOTFOUND scontent.xx.fbcdn.net
```
which seems to cause this error when I go to the instagram page on the site
![image](https://user-images.githubusercontent.com/1663379/73235699-822d6b00-415d-11ea-8ec5-0e18859ca193.png)

If you have any insight on that one please let me know!

**Comment by markkohdev** [comment]
^ Actually nvm about that I got it to work somehow -- not sure what I did but ¯\_(ツ)_/¯ 
Closing this and I'll open another ticket if I run into that issue again.

**Comment by rsipakov** [comment]
> Hey @markkohdev. You can find the PAGE_ID by going to your Facebook page and copying it from the url. When you go to your Facebook page the url should look something like this:
> 
> `https://www.facebook.com/[PAGE_NAME]-[PAGE_ID].`
> 
> Once you get the PAGE_ID you can make a GET request like this:
> 
> `[PAGE_ID]?fields=access_token`
> 
> Hope this helps. Let me know how it goes :).

[PAGE_ID] is you username or page name. For example, https://www.facebook.com/BMW/ for this case [PAGE_ID] is "bmw". Her is more correctly instructions https://www.npmjs.com/package/gatsby-source-instagram
