### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by liongkj** [LekoArts/gatsby-starter-portfolio-jodie#28]
![image](https://user-images.githubusercontent.com/20205301/55061216-26620380-50ae-11e9-8ae3-97266dcbc735.png)

Hi, i followed the readme instructions and try to build the website but failed. What did i missed? I tried on both my local machine and netlify build

**Comment by LekoArts** [comment]
I reproduced this issue with images that had no caption. I added a check to the title/caption. The API gives back a `null` if it's empty. You can see the commit on how to fix that.

**Comment by liongkj** [comment]
So gatsby build can only be run after registering for the facebook access token and stuff?

**Comment by LekoArts** [comment]
If you don't want to have an Instagram feed you can remove `src/pages/instagram` and the source plugin from `gatsby-config` :)
But if you leave those in, then yes, you have to define the necessary keys.
