### ISSUE TITLE
Npm run dev doesnt build - @babel/env

### ISSUE THREAD

**Issue by austriker27** [LekoArts/gatsby-starter-portfolio-jodie#77]
`Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
  Error: Cannot find module 'babel-preset-env' from .... Did you mean "@babel/env"?`

Do I need to update the babel install?

**Comment by austriker27** [comment]
I think my problem was I did a git clone instead of using the gatsby CLI to create a new project

**Comment by LekoArts** [comment]
Can't reproduce this with a new build, hope you figured it out. Thanks for using the starter :)
